server:
  port: 1101

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      # 配置默认数据源
      primary: fairybeauty
      datasource:
        fairybeauty:
          username: chenjianyun
          password: '@chensee123'
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp1uz4wc60klopi915o.mysql.rds.aliyuncs.com:3306/fairybeauty?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true

#swagger:
#  production: true

  redis:
    cluster:
      nodes: 127.0.0.1:6379
    password: redis@123
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

#flag:
#  isout: true

domain: fairuBeauty