server:
  port: 1101

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      # 配置默认数据源
      primary: fairybeauty
      datasource:
        fairybeauty:
          username: chenjianyun
          password: '@chensee123'
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-bp1uz4wc60klopi915o.mysql.rds.aliyuncs.com:3306/fairybeauty?characterEncoding=UTF-8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger:
#  production: true

  redis:
    cluster:
      nodes: 127.0.0.1:6379
#    password: redis@123
    keySerializer: org.springframework.data.redis.serializer.StringRedisSerializer
    valueSerializer: org.springframework.data.redis.serializer.StringRedisSerializer
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

#flag:
#  isout: true
checkLogin: false
domain: fairuBeauty
# 登陆缓存时间 单位天
loginTime: 3